import Head from "next/head";
import { getPosts } from "../services";
import { PostCard, PostWidget, Category } from "/components";

export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  return {
    props: { posts },
  };
}

export default function Home({ posts }) {
  console.log(posts);
  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>Nosirjonov&apos;s notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-8 col-span-1">
          {posts?.map((post) => (
            <PostCard post={post.node} key={post.node.createdAt} />
          ))}
        </div>
        <div className="lg:col-span-4 col-span-1">
          <div className="lg:sticky relative top-8">
            <PostWidget />
            <Category />
          </div>
        </div>
      </div>
    </div>
  );
}
